version: '3.9'

services:
  db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sanittas
    volumes:
      - ./db/data:/var/lib/mysql:rw
    restart: always
    ports:
      - 3306:3306
    networks:
      - sanittas
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -hlocalhost -uroot -proot"]
      timeout: 60s
      retries: 10
  imagelite-api:
    build: "./source/"
    container_name: imagelite-api
    restart: on-failure
    networks:
      - sanittas
    ports:
      - "8081:8080"
    depends_on:
      - db
  node-service:  # Adicionando o serviço Node.js
    image: node:latest  # Você pode substituir "latest" pela versão específica do Node.js que deseja usar
    container_name: node-service
    restart: always
    networks:
      - sanittas
    ports:
      - "80:3000"  # Porta utilizada pelo serviço Node.js
    # Outras configurações específicas do serviço Node.js podem ser adicionadas aqui
    volumes:
     - ./imagelite:/app
    command:
      - npm run dev
networks:
  sanittas:
    driver: bridge
