version: '3.9'

services:
  db:
    image: mysql
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sanittas
    volumes:
      - ./db/data:/var/lib/mysql:rw
    restart: always
    ports:
      - 3306:3306
    networks:
      - sanittas
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -hlocalhost -uroot -proot"]
      timeout: 60s
      retries: 10
  imagelite-api:
    build: "./source/"
    container_name: imagelite-api
    restart: on-failure
    networks:
      - sanittas
    ports:
      - "8081:8080"
    depends_on:
      - db
networks:
    sanittas:
      driver: bridge

    