spring:
  datasource:
    url: jdbc:postgresql://db:5432/imagelite?useSSL=false&allowPublicKeyRetrieval=true
    username: postgres
    password: postgres
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
